name: material
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  freezed_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  flutter_gen_runner: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
